name: crux

services:
  db:
    image: postgres:17.4
    container_name: crux-db
    env_file:
      - ./backend/.env
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    depends_on:
       - db
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "4001:4001"
    env_file:
      - ./backend/.env

  frontend:
    depends_on:
       - backend
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
      - NEXT_PUBLIC_API_URL=https://api.crux.kumarnitesh.in
    container_name: frontend
    ports:
      - "3001:3000"
    env_file:
      - ./frontend/.env

volumes:
  postgres_data:
